# config.yaml
# هذا هو ملف الإعدادات المركزي للنظام الخلفي (Backend)

# ===================================================================
# 1. إعدادات مزودي خدمة البحث عن الأخبار
# ===================================================================
search_providers:
  newsapi:
    api_key_env: "NEWS_API_KEY"
    base_url: "https://newsapi.org/v2/everything"
  gnews:
    api_key_env: "GNEWS_API_KEY"
    base_url: "https://gnews.io/api/v4/search"
  google_gemini:
    api_key_env: "GOOGLE_API_KEY"

# ===================================================================
# 2. معايير البحث العامة
# ===================================================================
search_parameters:
  languages: ['ar', 'en']
  default_period_days: 14
  max_articles_per_source: 100

# ===================================================================
# 3. إعدادات معالجة المحتوى
# ===================================================================
processing:
  deduplication_threshold: 0.9
  clustering:
    enabled: true
    min_cluster_size: 2

# ===================================================================
# 4. قوالب الأوامر لنموذج اللغة الكبير (LLM Prompts)
# ===================================================================
llm_prompts:
  # --- الأوامر القديمة (يمكن حذفها لاحقًا) ---
  ieee_topic_summary: >
    مهمتك هي أن تعمل كمحرر أخبار أكاديمي. سأعطيك مجموعة من المقاطع النصية التي تدور حول محور واحد ومحدد.
    التعليمات:
    1.  **التلخيص المركز**: قم بصياغة فقرة أو فقرتين تلخصان الأفكار الرئيسية والحقائق الواردة في هذه المقاطع **فقط**.
    2.  **التوثيق بأسلوب IEEE**: كل مقطع نصي سأقدمه لك سيكون مسبوقًا برقم مرجعي بين قوسين، مثل [1], [2], إلخ. عند استخدام معلومة من أي مقطع، **يجب عليك** إدراج رقمه المرجعي مباشرة بعد المعلومة.
    3.  **الحياد المطلق**: لا تقم بتحليل أو إعطاء رأي. اذكر الحقائق كما وردت في النصوص.
    المقاطع النصية للمحور الحالي:
    {context}
    اكتب الملخص لهذا المحور هنا:

  final_synthesis_prompt: >
    مهمتك هي أن تعمل كرئيس تحرير. سأقدم لك مجموعة من الملخصات التي تغطي محاور مختلفة لموضوع معين.
    التعليمات:
    1.  **اكتب ملخصًا تنفيذيًا**: في فقرة واحدة موجزة (2-3 جمل)، لخص أهم النقاط والاستنتاجات من جميع المحاور.
    2.  **اكتب خاتمة**: في فقرة واحدة، قدم نظرة شاملة تربط بين المحاور المختلفة.
    المدخلات:
    - سؤال المستخدم الأصلي: "{query}"
    - ملخصات المحاور:
    {topic_summaries}
    اكتب التقرير النهائي بالهيكل التالي بالضبط:
    ### ملخص تنفيذي
    [اكتب الملخص التنفيذي هنا]
    ### تفاصيل المحاور
    {topic_summaries}
    ### خاتمة
    [اكتب الخاتمة هنا]

  # --- الأوامر الجديدة للاستراتيجية المتقدمة ---
  fact_extraction_prompt: >
    مهمتك هي العمل كمحلل معلوماتي دقيق. سأعطيك مجموعة من نصوص المقالات الكاملة حول موضوع معين.
    التعليمات:
    1.  اقرأ جميع النصوص بعناية لفهم السياق الكامل.
    2.  استخرج قائمة بالحقائق والمعلومات الأساسية (مثل الأحداث، الأرقام، التصريحات، النتائج الرئيسية).
    3.  قدم كل حقيقة في جملة واحدة موجزة ومستقلة.
    4.  تجاهل الآراء الشخصية، التحليلات غير المدعومة، والمحتوى غير ذي الصلة.
    5.  لا تقم بترقيم القائمة أو استخدام (- *). افصل كل حقيقة بسطر جديد فقط.
    النصوص الكاملة للمقالات:
    {context}
    قائمة الحقائق المستخرجة:

  outline_generation_prompt: >
    مهمتك هي العمل كرئيس تحرير استراتيجي. سأعطيك موضوع البحث الأصلي وقائمة من الحقائق والمعلومات الخام التي تم استخلاصها.
    التعليمات:
    1.  حلل قائمة الحقائق لفهم الجوانب المختلفة للموضوع.
    2.  اقترح هيكلاً (Outline) منطقياً لمقال تحليلي متكامل حول الموضوع.
    3.  يجب أن يتكون الهيكل من 3 إلى 5 عناوين رئيسية (محاور).
    4.  يجب أن تكون العناوين مرتبة بشكل منطقي لخلق قصة متماسكة (مثلاً: مقدمة، تطورات، ردود أفعال، خاتمة).
    5.  اكتب العناوين المقترحة فقط، كل عنوان في سطر جديد. لا تقم بترقيمها أو إضافة أي نص آخر.
    موضوع البحث: "{query}"
    قائمة الحقائق الخام:
    {facts}
    الهيكل المقترح (العناوين فقط):

  # --- *** التصحيح هنا: تمت إزالة المسافة البادئة الزائدة *** ---
  topic_writing_prompt: >
    مهمتك هي العمل ككاتب محتوى خبير. سأعطيك عنوان محور (قسم) من مقال، وقائمة بالحقائق والمعلومات المتعلقة بهذا المحور فقط. كل حقيقة مسبوقة برقم مرجعي مثل [1], [2].

    التعليمات:
    1.  اكتب فقرة أو عدة فقرات مفصلة ومترابطة تشرح هذا المحور بعمق.
    2.  استخدم قائمة الحقائق المقدمة كمادة أساسية للكتابة.
    3.  **عند استخدام معلومة من حقيقة معينة، يجب عليك إدراج رقمها المرجعي مباشرة بعد المعلومة في النص الذي تكتبه.** مثال: "تدهورت الأوضاع الإنسانية بشكل ملحوظ [3]."
    4.  لا تكتفِ بسرد الحقائق، بل ادمجها في نص سلس ومترابط.
    5.  أعد صياغة الأفكار بأسلوبك الخاص وحافظ على تدفق منطقي للنص.

    عنوان المحور: "{topic_title}"

    الحقائق المتعلقة بهذا المحور مع مراجعها:
    {facts}

    المحتوى المكتوب لهذا المحور (مع تضمين المراجع):

  final_report_assembly_prompt: >
    مهمتك هي العمل كرئيس تحرير نهائي. سأعطيك موضوع البحث الأصلي ومجموعة من الأقسام (المحاور) المكتوبة التي تشكل المقال الكامل.
    التعليمات:
    1.  اقرأ جميع الأقسام المكتوبة لفهم القصة الكاملة.
    2.  اكتب "ملخصًا تنفيذيًا" موجزًا (2-3 جمل) يوضع في بداية المقال.
    3.  اكتب "خاتمة" مناسبة تربط الأفكار الرئيسية وتقدم نظرة نهائية.
    4.  قم بتجميع التقرير بالهيكل التالي بالضبط، مع الحفاظ على محتوى الأقسام كما هو.
    موضوع البحث: "{query}"
    الأقسام المكتوبة:
    {written_topics}
    التقرير النهائي المجمع:
    ### ملخص تنفيذي
    [اكتب الملخص التنفيذي هنا]
    {written_topics}
    ### خاتمة
    [اكتب الخاتمة هنا]

# ===================================================================
# 5. إدارة المصادر الإخبارية (للتوسع المستقبلي)
# ===================================================================
sources:
  allowlist: []
  blocklist: []
